name = "2gc-chat-secure"
main = "src/server/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { 
  ENABLE_BOT_PROTECTION = "true"
}

[env.development]
vars = { 
  ENABLE_BOT_PROTECTION = "true"
}

[[env.production.durable_objects.bindings]]
name = "CHAT"
class_name = "Chat"

[[env.development.durable_objects.bindings]]
name = "CHAT"
class_name = "Chat"
