name = "2gc-chat-secure"
main = "src/server/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENABLE_BOT_PROTECTION = "true"

[env.production]
vars = { 
  ENABLE_BOT_PROTECTION = "true",
  CHAT_PASSWORD = "password123"
}

[[env.production.durable_objects.bindings]]
name = "CHAT"
class_name = "Chat"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "Chat"
